;;; Generated by Verrazano 0.5
;;; WARNING: This is a generated file, editing it is unwise!


(cl:in-package :cl-user)

(cl:defpackage :osg-viewer-cffi-bindings
  (:use :cffi)
  (:nicknames)
  (:export "VIEWER-INIT"
           "CONSTRUCTOR-INIT"
           "GET-USAGE"
           "MAP-<STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> >,STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> >,STD-::LESS-<STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> > >,STD-::ALLOCATOR-<STD-::PAIR-<CONST- STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> >, STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> > > > >"
           "APPLICATION-USAGE"
           "VECTOR-<OSG-VIEWER-::-VIEW-*,STD-::ALLOCATOR-<OSG-VIEWER-::-VIEW-*> >"
           "GET-VIEWS"
           "VECTOR-<OSG-VIEWER-::-SCENE-*,STD-::ALLOCATOR-<OSG-VIEWER-::-SCENE-*> >"
           "GET-SCENES"
           "VECTOR-<OSG-::-OPERATION-THREAD-*,STD-::ALLOCATOR-<OSG-::-OPERATION-THREAD-*> >"
           "GET-OPERATION-THREADS"
           "VECTOR-<-OPEN-THREADS-::-THREAD-*,STD-::ALLOCATOR-<-OPEN-THREADS-::-THREAD-*> >"
           "GET-ALL-THREADS"
           "VECTOR-<OSG-::-GRAPHICS-CONTEXT-*,STD-::ALLOCATOR-<OSG-::-GRAPHICS-CONTEXT-*> >"
           "GET-CONTEXTS"
           "VECTOR-<OSG-::-CAMERA-*,STD-::ALLOCATOR-<OSG-::-CAMERA-*> >"
           "GET-CAMERAS"
           "GET-CAMERA-WITH-FOCUS"
           "SET-CAMERA-WITH-FOCUS"
           "REF-PTR-<OSG-::-CAMERA-::-DRAW-CALLBACK->"
           "REF-PTR-<OSG-::-OBJECT->"
           "REF-PTR-<OSG-::-GRAPHICS-OPERATION->"
           "REF-PTR-<OSG-::-GRAPHICS-CONTEXT->"
           "REF-PTR-<OSG-::-OPERATION-THREAD->"
           "MAP-<OSG-::-CAMERA-::-BUFFER-COMPONENT-,OSG-::-CAMERA-::-ATTACHMENT-,STD-::LESS-<OSG-::-CAMERA-::-BUFFER-COMPONENT->,STD-::ALLOCATOR-<STD-::PAIR-<CONST- OSG-::-CAMERA-::-BUFFER-COMPONENT-, OSG-::-CAMERA-::-ATTACHMENT-> > >"
           "REF-PTR-<OSG-::-VIEWPORT->"
           "REF-PTR-<OSG-::-COLOR-MASK->"
           "CAMERA"
           "SEPERATE-WINDOW"
           "FRAME-BUFFER"
           "PIXEL-BUFFER"
           "PIXEL-BUFFER-RTT"
           "FRAME-BUFFER-OBJECT"
           "RENDER-TARGET-IMPLEMENTATION"
           "G-LENUM"
           "POST-RENDER"
           "NESTED-RENDER"
           "PRE-RENDER"
           "RENDER-ORDER"
           "MATRIXD"
           "VERTICAL"
           "HORIZONTAL"
           "FIXED"
           "PROJECTION-RESIZE-POLICY"
           "POST-MULTIPLY"
           "PRE-MULTIPLY"
           "TRANSFORM-ORDER"
           "VEC-4"
           "VEC-4F"
           "G-LBITFIELD"
           "REF-PTR-<OSG-::-FRAME-STAMP->"
           "VECTOR-<OSG-::-VIEW-::-SLAVE-,STD-::ALLOCATOR-<OSG-::-VIEW-::-SLAVE-> >"
           "REF-PTR-<OSG-::-CAMERA->"
           "REF-PTR-<OSG-::-LIGHT->"
           "REF-PTR-<OSG-::-STATS->"
           "SKY-LIGHT"
           "HEADLIGHT"
           "NO-LIGHT"
           "LIGHTING-MODE"
           "UPDATE-TRAVERSAL"
           "EVENT-TRAVERSAL"
           "ADVANCE"
           "RUN"
           "GET-VIEWER-FRAME-STAMP"
           "TM-ISDST"
           "TM-YDAY"
           "TM-WDAY"
           "TM-YEAR"
           "TM-MON"
           "TM-MDAY"
           "TM-HOUR"
           "TM-MIN"
           "TM-SEC"
           "FRAME-STAMP"
           "ELAPSED-TIME"
           "SET-UP-VIEWER-AS-EMBEDDED-IN-WINDOW"
           "GRAPHICS-WINDOW-EMBEDDED"
           "SET-SCENE-DATA"
           "REF-PTR-<OSG-::-STATE-SET->"
           "VECTOR-<STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> >,STD-::ALLOCATOR-<STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> > > >"
           "REF-PTR-<OSG-::-NODE-CALLBACK->"
           "VECTOR-<OSG-::-GROUP-*,STD-::ALLOCATOR-<OSG-::-GROUP-*> >"
           "REF-PTR-<OSG-::-NODE-::-COMPUTE-BOUNDING-SPHERE-CALLBACK->"
           "NODE"
           "BOUNDING-SPHERE"
           "BOUNDING-SPHERE-IMPL-<OSG-::-VEC-3F->"
           "BOUNDING-SPHEREF"
           "SET-REFERENCE-TIME"
           "SET-START-TICK"
           "REALIZE"
           "IS-REALIZED"
           "READ-CONFIGURATION"
           "GET-VIEWER-STATS"
           "SET-VIEWER-STATS"
           "MAP-<STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> >,BOOL-,STD-::LESS-<STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> > >,STD-::ALLOCATOR-<STD-::PAIR-<CONST- STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> >, BOOL-> > >"
           "MAP-<STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> >,DOUBLE-,STD-::LESS-<STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> > >,STD-::ALLOCATOR-<STD-::PAIR-<CONST- STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> >, DOUBLE-> > >"
           "VECTOR-<STD-::MAP-<STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> >, DOUBLE-, STD-::LESS-<STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> > >, STD-::ALLOCATOR-<STD-::PAIR-<CONST- STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> >, DOUBLE-> > >,STD-::ALLOCATOR-<STD-::MAP-<STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> >, DOUBLE-, STD-::LESS-<STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> > >, STD-::ALLOCATOR-<STD-::PAIR-<CONST- STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> >, DOUBLE-> > > > >"
           "STATS"
           "MUTEX"
           "TAKE"
           "REF-PTR-<OSG-::-DISPLAY-SETTINGS->"
           "VECTOR-<OSG-::OBSERVER-PTR-<OSG-::-NODE->,STD-::ALLOCATOR-<OSG-::OBSERVER-PTR-<OSG-::-NODE-> > >"
           "LIST-<OSG-::REF-PTR-<OSG-GA-::GUI-EVENT-HANDLER->,STD-::ALLOCATOR-<OSG-::REF-PTR-<OSG-GA-::GUI-EVENT-HANDLER-> > >" 
           "REF-PTR-<OSG-GA-::-MATRIX-MANIPULATOR->"
           "REF-PTR-<OSG-GA-::-EVENT-QUEUE->"
           "REF-PTR-<OSG-VIEWER-::-SCENE->"
           "OBSERVER-PTR-<OSG-VIEWER-::-VIEWER-BASE->"
           "VIEW"
           "PROPORTIONAL-TO-SCREEN-DISTANCE"
           "USE-FUSION-DISTANCE-VALUE"
           "FUSION-DISTANCE-MODE"
           "TIMER-T"
           "CLASS-NAME"
           "LIBRARY-NAME"
           "IS-SAME-KIND-AS"
           "CLONE"
           "CLONE-TYPE"
           "REF-PTR-<OSG-::-REFERENCED->"
           "OBJECT"
           "UNSPECIFIED"
           "STATIC"
           "DYNAMIC"
           "DATA-VARIANCE"
           "BASIC-STRING-<CHAR-,STD-::CHAR-TRAITS-<CHAR->,STD-::ALLOCATOR-<CHAR-> >"
           "STRING"
           "COPY-OP"
           "REF-PTR-<OSG-::-APPLICATION-USAGE->"
           "MAP-<STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> >,OSG-::-ARGUMENT-PARSER-::-ERROR-SEVERITY-,STD-::LESS-<STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> > >,STD-::ALLOCATOR-<STD-::PAIR-<CONST- STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> >, OSG-::-ARGUMENT-PARSER-::-ERROR-SEVERITY-> > >"
           "ARGUMENT-PARSER"
           "VIEWER-NEW"
           "VIEWER-CONSTRUCTOR"
           "OBSERVER-PTR-<OSG-::-CAMERA->"
           "VIEWER"
           "+_ZTIN-9OSG-VIEWER-6-VIEWER-E+"))

(cl:in-package :osg-viewer-cffi-bindings)

(cl:defun vtable-lookup (pobj indx coff)
  (cl:let ((vptr (cffi:mem-ref pobj :pointer coff)))
    (cffi:mem-aref vptr :pointer (cl:- indx 2))))

(cl:defmacro virtual-funcall (pobj indx coff cl:&body body)
  `(cffi:foreign-funcall-pointer (vtable-lookup ,pobj ,indx ,coff) ,cl:nil ,@body))

(cl:defconstant +_ztin-9osg-viewer-6-viewer-e+ cl:nil)

(cffi:defcstruct viewer
  (_camera-with-focus observer-ptr-<osg-::-camera->))

(cffi:defcfun ("_ZN9osgViewer6ViewerC1Ev" viewer-constructor) :void (this :pointer))

(cl:defun viewer-new ()
  (cl:let ((instance (cffi:foreign-alloc 'viewer)))
    (viewer-constructor instance)
    instance))

(cffi:defcstruct argument-parser
  (_argc (:pointer :int))
  (_argv :pointer)
  (_error-message-map map-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >,osg-::-argument-parser-::-error-severity-,std-::less-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> > >,std-::allocator-<std-::pair-<const- std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >, osg-::-argument-parser-::-error-severity-> > >)
  (_usage ref-ptr-<osg-::-application-usage->))

(cffi:defcfun ("_ZN9osgViewer6ViewerC1ERN3osg14ArgumentParserE" viewer-constructor) :void (this :pointer)
                                                                                          (arguments argument-parser))

(cl:defun viewer-new ()
  (cl:let ((instance (cffi:foreign-alloc 'viewer)))
    (viewer-constructor instance)
    instance))

(cffi:defcstruct copy-op
  (_flags :unsigned-int))

(cffi:defcfun ("_ZN9osgViewer6ViewerC1ERKS0_RKN3osg6CopyOpE" viewer-constructor) :void (this :pointer)
                                                                                       (viewer viewer)
                                                                                       (copyop copy-op))

(cl:defun viewer-new ()
  (cl:let ((instance (cffi:foreign-alloc 'viewer)))
    (viewer-constructor instance)
    instance))

(cffi::defctype string basic-string-<char-,std-::char-traits-<char->,std-::allocator-<char-> >)

(cffi:defcenum data-variance
  (:dynamic 0)
  (:static 1)
  (:unspecified 2))

(cffi:defcstruct object
  (_name string)
  (_data-variance data-variance)
  (_user-data ref-ptr-<osg-::-referenced->))

(cffi:defcfun ("_ZNK9osgViewer6Viewer9cloneTypeEv" clone-type) :pointer (this :pointer))

(cffi:defcfun ("_ZNK9osgViewer6Viewer5cloneERKN3osg6CopyOpE" clone) :pointer (this :pointer)
                                                                             (copyop copy-op))

(cffi:defcfun ("_ZNK9osgViewer6Viewer12isSameKindAsEPKN3osg6ObjectE" is-same-kind-as) :char (this :pointer)
                                                                                            (obj :pointer))

(cffi:defcfun ("_ZNK9osgViewer6Viewer11libraryNameEv" library-name) :pointer (this :pointer))

(cffi:defcfun ("_ZNK9osgViewer6Viewer9classNameEv" class-name) :pointer (this :pointer))

(cffi::defctype timer-t :unsigned-long-long)

(cffi:defcenum fusion-distance-mode
  (:use-fusion-distance-value 0)
  (:proportional-to-screen-distance 1))

(cffi:defcstruct view
  (_viewer-base observer-ptr-<osg-viewer-::-viewer-base->)
  (_start-tick timer-t)
  (_scene ref-ptr-<osg-viewer-::-scene->)
  (_event-queue ref-ptr-<osg-ga-::-event-queue->)
  (_camera-manipulator ref-ptr-<osg-ga-::-matrix-manipulator->)
  (_event-handlers list-<osg-::ref-ptr-<osg-ga-::gui-event-handler->,std-::allocator-<osg-::ref-ptr-<osg-ga-::gui-event-handler-> > >)
  (_coordinate-system-node-path vector-<osg-::observer-ptr-<osg-::-node->,std-::allocator-<osg-::observer-ptr-<osg-::-node-> > >)
  (_display-settings ref-ptr-<osg-::-display-settings->)
  (_fusion-distance-mode fusion-distance-mode)
  (_fusion-distance-value :float))

(cffi:defcfun ("_ZN9osgViewer6Viewer4takeERNS_4ViewE" take) :void (this :pointer) (rhs view))

(cffi:defcstruct mutex
  (_prv-data (:pointer :void)))

(cffi:defcstruct stats
  (_name string)
  (_mutex mutex)
  (_base-frame-number :int)
  (_latest-frame-number :int)
  (_attribute-map-list vector-<std-::map-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >, double-, std-::less-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> > >, std-::allocator-<std-::pair-<const- std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >, double-> > >,std-::allocator-<std-::map-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >, double-, std-::less-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> > >, std-::allocator-<std-::pair-<const- std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >, double-> > > > >)
  (_invalid-attribute-map map-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >,double-,std-::less-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> > >,std-::allocator-<std-::pair-<const- std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >, double-> > >)
  (_collect-map map-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >,bool-,std-::less-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> > >,std-::allocator-<std-::pair-<const- std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >, bool-> > >))

(cffi:defcfun ("_ZN9osgViewer6Viewer14setViewerStatsEPN3osg5StatsE" set-viewer-stats) :void (this :pointer)
                                                                                            (stats :pointer))

(cffi:defcfun ("_ZN9osgViewer6Viewer14getViewerStatsEv" get-viewer-stats) :pointer (this :pointer))

(cffi:defcfun ("_ZNK9osgViewer6Viewer14getViewerStatsEv" get-viewer-stats) :pointer (this :pointer))

(cffi:defcfun ("_ZN9osgViewer6Viewer17readConfigurationERKSs" read-configuration) :char (this :pointer)
                                                                                        (filename string))

(cffi:defcfun ("_ZNK9osgViewer6Viewer10isRealizedEv" is-realized) :char (this :pointer))

(cffi:defcfun ("_ZN9osgViewer6Viewer7realizeEv" realize) :void (this :pointer))

(cffi:defcfun ("_ZN9osgViewer6Viewer12setStartTickEy" set-start-tick) :void (this :pointer)
                                                                            (tick timer-t))

(cffi:defcfun ("_ZN9osgViewer6Viewer16setReferenceTimeEd" set-reference-time) :void (this :pointer)
                                                                                    (time :double))

(cffi::defctype bounding-spheref bounding-sphere-impl-<osg-::-vec-3f->)

(cffi::defctype bounding-sphere bounding-spheref)

(cffi:defcstruct node
  (_initial-bound bounding-sphere)
  (_compute-bound-callback ref-ptr-<osg-::-node-::-compute-bounding-sphere-callback->)
  (_bounding-sphere bounding-sphere)
  (_bounding-sphere-computed :char)
  (_parents vector-<osg-::-group-*,std-::allocator-<osg-::-group-*> >)
  (_update-callback ref-ptr-<osg-::-node-callback->)
  (_num-children-requiring-update-traversal :unsigned-int)
  (_event-callback ref-ptr-<osg-::-node-callback->)
  (_num-children-requiring-event-traversal :unsigned-int)
  (_cull-callback ref-ptr-<osg-::-node-callback->)
  (_culling-active :char)
  (_num-children-with-culling-disabled :unsigned-int)
  (_num-children-with-occluder-nodes :unsigned-int)
  (_node-mask :unsigned-int)
  (_descriptions vector-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >,std-::allocator-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> > > >)
  (_stateset ref-ptr-<osg-::-state-set->))

(cffi:defcfun ("_ZN9osgViewer6Viewer12setSceneDataEPN3osg4NodeE" set-scene-data) :void (this :pointer)
                                                                                       (node :pointer))

(cffi:defcstruct graphics-window-embedded
  )

(cffi:defcfun ("_ZN9osgViewer6Viewer29setUpViewerAsEmbeddedInWindowEiiii" set-up-viewer-as-embedded-in-window) :pointer (this :pointer)
                                                                                                                        (x :int)
                                                                                                                        (y :int)
                                                                                                                        (width :int)
                                                                                                                        (height :int))

(cffi:defcfun ("_ZN9osgViewer6Viewer11elapsedTimeEv" elapsed-time) :double (this :pointer))

(cffi:defcstruct frame-stamp
  (_frame-number :int)
  (_reference-time :double)
  (_simulation-time :double)
  (tm-sec :int)
  (tm-min :int)
  (tm-hour :int)
  (tm-mday :int)
  (tm-mon :int)
  (tm-year :int)
  (tm-wday :int)
  (tm-yday :int)
  (tm-isdst :int))

(cffi:defcfun ("_ZN9osgViewer6Viewer19getViewerFrameStampEv" get-viewer-frame-stamp) :pointer (this :pointer))

(cffi:defcfun ("_ZN9osgViewer6Viewer3runEv" run) :int (this :pointer))

(cffi:defcfun ("_ZN9osgViewer6Viewer7advanceEd" advance) :void (this :pointer)
                                                               (simulation-time :double))

(cffi:defcfun ("_ZN9osgViewer6Viewer14eventTraversalEv" event-traversal) :void (this :pointer))

(cffi:defcfun ("_ZN9osgViewer6Viewer15updateTraversalEv" update-traversal) :void (this :pointer))

(cffi:defcenum lighting-mode
  (:no-light 0)
  (:headlight 1)
  (:sky-light 2))

(cffi:defcstruct view
  (_stats ref-ptr-<osg-::-stats->)
  (_lighting-mode lighting-mode)
  (_light ref-ptr-<osg-::-light->)
  (_camera ref-ptr-<osg-::-camera->)
  (_slaves vector-<osg-::-view-::-slave-,std-::allocator-<osg-::-view-::-slave-> >)
  (_frame-stamp ref-ptr-<osg-::-frame-stamp->))

(cffi::defctype g-lbitfield :unsigned-int)

(cffi:defcstruct vec-4f
  (_v :float :count 4))

(cffi::defctype vec-4 vec-4f)

(cffi:defcenum transform-order
  (:pre-multiply 0)
  (:post-multiply 1))

(cffi:defcenum projection-resize-policy
  (:fixed 0)
  (:horizontal 1)
  (:vertical 2))

(cffi:defcstruct matrixd
  (_mat :double :count 4 :count 4))

(cffi:defcenum render-order
  (:pre-render 0)
  (:nested-render 1)
  (:post-render 2))

(cffi::defctype g-lenum :unsigned-int)

(cffi:defcenum render-target-implementation
  (:frame-buffer-object 0)
  (:pixel-buffer-rtt 1)
  (:pixel-buffer 2)
  (:frame-buffer 3)
  (:seperate-window 4))

(cffi:defcstruct camera
  (_data-change-mutex mutex)
  (_view :pointer)
  (_stats ref-ptr-<osg-::-stats->)
  (_allow-event-focus :char)
  (_display-settings ref-ptr-<osg-::-display-settings->)
  (_clear-mask g-lbitfield)
  (_clear-color vec-4)
  (_clear-accum vec-4)
  (_clear-depth :double)
  (_clear-stencil :int)
  (_color-mask ref-ptr-<osg-::-color-mask->)
  (_viewport ref-ptr-<osg-::-viewport->)
  (_transform-order transform-order)
  (_projection-resize-policy projection-resize-policy)
  (_projection-matrix matrixd)
  (_view-matrix matrixd)
  (_render-order render-order)
  (_render-order-num :int)
  (_draw-buffer g-lenum)
  (_read-buffer g-lenum)
  (_render-target-implementation render-target-implementation)
  (_render-target-fallback render-target-implementation)
  (_buffer-attachment-map map-<osg-::-camera-::-buffer-component-,osg-::-camera-::-attachment-,std-::less-<osg-::-camera-::-buffer-component->,std-::allocator-<std-::pair-<const- osg-::-camera-::-buffer-component-, osg-::-camera-::-attachment-> > >)
  (_camera-thread ref-ptr-<osg-::-operation-thread->)
  (_graphics-context ref-ptr-<osg-::-graphics-context->)
  (_renderer ref-ptr-<osg-::-graphics-operation->)
  (_rendering-cache ref-ptr-<osg-::-object->)
  (_initial-draw-callback ref-ptr-<osg-::-camera-::-draw-callback->)
  (_pre-draw-callback ref-ptr-<osg-::-camera-::-draw-callback->)
  (_post-draw-callback ref-ptr-<osg-::-camera-::-draw-callback->)
  (_final-draw-callback ref-ptr-<osg-::-camera-::-draw-callback->))

(cffi:defcfun ("_ZN9osgViewer6Viewer18setCameraWithFocusEPN3osg6CameraE" set-camera-with-focus) :void (this :pointer)
                                                                                                      (camera :pointer))

(cffi:defcfun ("_ZN9osgViewer6Viewer18getCameraWithFocusEv" get-camera-with-focus) :pointer (this :pointer))

(cffi:defcfun ("_ZNK9osgViewer6Viewer18getCameraWithFocusEv" get-camera-with-focus) :pointer (this :pointer))

(cffi:defcfun ("_ZN9osgViewer6Viewer10getCamerasERSt6vectorIPN3osg6CameraESaIS4_EEb" get-cameras) :void (this :pointer)
                                                                                                        (cameras vector-<osg-::-camera-*,std-::allocator-<osg-::-camera-*> >)
                                                                                                        (only-active :char))

(cffi:defcfun ("_ZN9osgViewer6Viewer11getContextsERSt6vectorIPN3osg15GraphicsContextESaIS4_EEb" get-contexts) :void (this :pointer)
                                                                                                                    (contexts vector-<osg-::-graphics-context-*,std-::allocator-<osg-::-graphics-context-*> >)
                                                                                                                    (only-valid :char))

(cffi:defcfun ("_ZN9osgViewer6Viewer13getAllThreadsERSt6vectorIPN11OpenThreads6ThreadESaIS4_EEb" get-all-threads) :void (this :pointer)
                                                                                                                        (threads vector-<-open-threads-::-thread-*,std-::allocator-<-open-threads-::-thread-*> >)
                                                                                                                        (only-active :char))

(cffi:defcfun ("_ZN9osgViewer6Viewer19getOperationThreadsERSt6vectorIPN3osg15OperationThreadESaIS4_EEb" get-operation-threads) :void (this :pointer)
                                                                                                                                     (threads vector-<osg-::-operation-thread-*,std-::allocator-<osg-::-operation-thread-*> >)
                                                                                                                                     (only-active :char))

(cffi:defcfun ("_ZN9osgViewer6Viewer9getScenesERSt6vectorIPNS_5SceneESaIS3_EEb" get-scenes) :void (this :pointer)
                                                                                                  (scenes vector-<osg-viewer-::-scene-*,std-::allocator-<osg-viewer-::-scene-*> >)
                                                                                                  (only-valid :char))

(cffi:defcfun ("_ZN9osgViewer6Viewer8getViewsERSt6vectorIPNS_4ViewESaIS3_EEb" get-views) :void (this :pointer)
                                                                                               (views vector-<osg-viewer-::-view-*,std-::allocator-<osg-viewer-::-view-*> >)
                                                                                               (only-valid :char))

(cffi:defcstruct application-usage
  (_application-name string)
  (_description string)
  (_command-line-usage string)
  (_command-line-options map-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >,std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >,std-::less-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> > >,std-::allocator-<std-::pair-<const- std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >, std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> > > > >)
  (_environmental-variables map-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >,std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >,std-::less-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> > >,std-::allocator-<std-::pair-<const- std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >, std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> > > > >)
  (_keyboard-mouse map-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >,std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >,std-::less-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> > >,std-::allocator-<std-::pair-<const- std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >, std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> > > > >)
  (_environmental-variables-defaults map-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >,std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >,std-::less-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> > >,std-::allocator-<std-::pair-<const- std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >, std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> > > > >)
  (_command-line-options-defaults map-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >,std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >,std-::less-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> > >,std-::allocator-<std-::pair-<const- std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >, std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> > > > >))

(cffi:defcfun ("_ZNK9osgViewer6Viewer8getUsageERN3osg16ApplicationUsageE" get-usage) :void (this :pointer)
                                                                                           (usage application-usage))

(cffi:defcfun ("_ZN9osgViewer6Viewer15constructorInitEv" constructor-init) :void (this :pointer))

(cffi:defcfun ("_ZN9osgViewer6Viewer10viewerInitEv" viewer-init) :void (this :pointer))
