;;; Generated by Verrazano 0.5
;;; WARNING: This is a generated file, editing it is unwise!


(cl:in-package :cl-user)

(cl:defpackage :osg-ga-cffi-bindings
  (:use :cffi)
  (:nicknames)
  (:export "IS-MOUSE-MOVING"
           "TB-PROJECT-TO-SPHERE"
           "TRACKBALL"
           "CALC-MOVEMENT"
           "COMPUTE-POSITION"
           "VEC-3"
           "VEC-3F"
           "ADD-MOUSE-EVENT"
           "FLUSH-MOUSE-EVENT-STACK"
           "GET-TRACKBALL-SIZE"
           "SET-TRACKBALL-SIZE"
           "GET-DISTANCE"
           "SET-DISTANCE"
           "GET-ROTATION"
           "SET-ROTATION"
           "GET-CENTER"
           "SET-CENTER"
           "GET-MINIMUM-ZOOM-SCALE"
           "SET-MINIMUM-ZOOM-SCALE"
           "GET-USAGE"
           "MAP-<STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> >,STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> >,STD-::LESS-<STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> > >,STD-::ALLOCATOR-<STD-::PAIR-<CONST- STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> >, STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> > > > >"
           "APPLICATION-USAGE"
           "BASIC-STRING-<CHAR-,STD-::CHAR-TRAITS-<CHAR->,STD-::ALLOCATOR-<CHAR-> >"
           "STRING"
           "HANDLE"
           "INIT"
           "HOME"
           "GUI-ACTION-ADAPTER"
           "OBSERVER-PTR-<OSG-::-GRAPHICS-CONTEXT->"
           "GUI-EVENT-ADAPTER"
           "ERASER"
           "PUCK"
           "PEN"
           "UNKNOWN"
           "TABLET-POINTER-TYPE"
           "Y-INCREASING-DOWNWARDS"
           "Y-INCREASING-UPWARDS"
           "MOUSE-Y-ORIENTATION"
           "SCROLL-2D"
           "SCROLL-DOWN"
           "SCROLL-UP"
           "SCROLL-RIGHT"
           "SCROLL-LEFT"
           "SCROLL-NONE"
           "SCROLLING-MOTION"
           "USER"
           "QUIT-APPLICATION"
           "CLOSE-WINDOW"
           "PEN-PROXIMITY-LEAVE"
           "PEN-PROXIMITY-ENTER"
           "PEN-ORIENTATION"
           "PEN-PRESSURE"
           "SCROLL"
           "RESIZE"
           "FRAME"
           "KEYUP"
           "KEYDOWN"
           "MOVE"
           "DRAG"
           "DOUBLECLICK"
           "RELEASE"
           "PUSH"
           "NONE"
           "EVENT-TYPE"
           "GET-NODE"
           "SET-NODE"
           "REF-PTR-<OSG-::-STATE-SET->"
           "VECTOR-<STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> >,STD-::ALLOCATOR-<STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> > > >"
           "REF-PTR-<OSG-::-NODE-CALLBACK->"
           "VECTOR-<OSG-::-GROUP-*,STD-::ALLOCATOR-<OSG-::-GROUP-*> >"
           "REF-PTR-<OSG-::-NODE-::-COMPUTE-BOUNDING-SPHERE-CALLBACK->"
           "NODE"
           "BOUNDING-SPHERE"
           "BOUNDING-SPHERE-IMPL-<OSG-::-VEC-3F->"
           "BOUNDING-SPHEREF"
           "GET-FUSION-DISTANCE-VALUE"
           "GET-FUSION-DISTANCE-MODE"
           "PROPORTIONAL-TO-SCREEN-DISTANCE"
           "USE-FUSION-DISTANCE-VALUE"
           "FUSION-DISTANCE-MODE"
           "GET-INVERSE-MATRIX"
           "GET-MATRIX"
           "SET-BY-INVERSE-MATRIX"
           "SET-BY-MATRIX"
           "MATRIXD"
           "CLASS-NAME"
           "TRACKBALL-MANIPULATOR-NEW"
           "TRACKBALL-MANIPULATOR-CONSTRUCTOR"
           "REF-PTR-<OSG-::-NODE->"
           "REF-PTR-<CONST- OSG-GA-::GUI-EVENT-ADAPTER->"
           "TRACKBALL-MANIPULATOR"
           "QUAT"
           "VEC-3D"
           "+_ZTIN-5OSG-GA-20-TRACKBALL-MANIPULATOR-E+"))

(cl:in-package :osg-ga-cffi-bindings)

(cl:defun vtable-lookup (pobj indx coff)
  (cl:let ((vptr (cffi:mem-ref pobj :pointer coff)))
    (cffi:mem-aref vptr :pointer (cl:- indx 2))))

(cl:defmacro virtual-funcall (pobj indx coff cl:&body body)
  `(cffi:foreign-funcall-pointer (vtable-lookup ,pobj ,indx ,coff) ,cl:nil ,@body))

(cl:defconstant +_ztin-5osg-ga-20-trackball-manipulator-e+ cl:nil)

(cffi:defcstruct vec-3d
  (_v :double :count 3))

(cffi:defcstruct quat
  (_v :double :count 4))

(cffi:defcstruct trackball-manipulator
  (_ga-t-1 ref-ptr-<const- osg-ga-::gui-event-adapter->)
  (_ga-t-0 ref-ptr-<const- osg-ga-::gui-event-adapter->)
  (_node ref-ptr-<osg-::-node->)
  (_model-scale :double)
  (_minimum-zoom-scale :double)
  (_thrown :char)
  (_center vec-3d)
  (_rotation quat)
  (_distance :double)
  (_trackball-size :float))

(cffi:defcfun ("_ZN5osgGA20TrackballManipulatorC1ERKS0_" trackball-manipulator-constructor) :void (this :pointer)
                                                                                                  (arg1 trackball-manipulator))

(cl:defun trackball-manipulator-new ()
  (cl:let ((instance (cffi:foreign-alloc 'trackball-manipulator)))
    (trackball-manipulator-constructor instance)
    instance))

(cffi:defcfun ("_ZN5osgGA20TrackballManipulatorC1Ev" trackball-manipulator-constructor) :void (this :pointer))

(cl:defun trackball-manipulator-new ()
  (cl:let ((instance (cffi:foreign-alloc 'trackball-manipulator)))
    (trackball-manipulator-constructor instance)
    instance))

(cffi:defcfun ("_ZNK5osgGA20TrackballManipulator9classNameEv" class-name) :pointer (this :pointer))

(cffi:defcstruct matrixd
  (_mat :double :count 4 :count 4))

(cffi:defcfun ("_ZN5osgGA20TrackballManipulator11setByMatrixERKN3osg7MatrixdE" set-by-matrix) :void (this :pointer)
                                                                                                    (matrix matrixd))

(cffi:defcfun ("_ZN5osgGA20TrackballManipulator18setByInverseMatrixERKN3osg7MatrixdE" set-by-inverse-matrix) :void (this :pointer)
                                                                                                                   (matrix matrixd))

(cffi:defcfun ("_ZNK5osgGA20TrackballManipulator9getMatrixEv" get-matrix) matrixd (this :pointer))

(cffi:defcfun ("_ZNK5osgGA20TrackballManipulator16getInverseMatrixEv" get-inverse-matrix) matrixd (this :pointer))

(cffi:defcenum fusion-distance-mode
  (:use-fusion-distance-value 0)
  (:proportional-to-screen-distance 1))

(cffi:defcfun ("_ZNK5osgGA20TrackballManipulator21getFusionDistanceModeEv" get-fusion-distance-mode) fusion-distance-mode (this :pointer))

(cffi:defcfun ("_ZNK5osgGA20TrackballManipulator22getFusionDistanceValueEv" get-fusion-distance-value) :float (this :pointer))

(cffi::defctype bounding-spheref bounding-sphere-impl-<osg-::-vec-3f->)

(cffi::defctype bounding-sphere bounding-spheref)

(cffi:defcstruct node
  (_initial-bound bounding-sphere)
  (_compute-bound-callback ref-ptr-<osg-::-node-::-compute-bounding-sphere-callback->)
  (_bounding-sphere bounding-sphere)
  (_bounding-sphere-computed :char)
  (_parents vector-<osg-::-group-*,std-::allocator-<osg-::-group-*> >)
  (_update-callback ref-ptr-<osg-::-node-callback->)
  (_num-children-requiring-update-traversal :unsigned-int)
  (_event-callback ref-ptr-<osg-::-node-callback->)
  (_num-children-requiring-event-traversal :unsigned-int)
  (_cull-callback ref-ptr-<osg-::-node-callback->)
  (_culling-active :char)
  (_num-children-with-culling-disabled :unsigned-int)
  (_num-children-with-occluder-nodes :unsigned-int)
  (_node-mask :unsigned-int)
  (_descriptions vector-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >,std-::allocator-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> > > >)
  (_stateset ref-ptr-<osg-::-state-set->))

(cffi:defcfun ("_ZN5osgGA20TrackballManipulator7setNodeEPN3osg4NodeE" set-node) :void (this :pointer)
                                                                                      (arg1 :pointer))

(cffi:defcfun ("_ZNK5osgGA20TrackballManipulator7getNodeEv" get-node) :pointer (this :pointer))

(cffi:defcfun ("_ZN5osgGA20TrackballManipulator7getNodeEv" get-node) :pointer (this :pointer))

(cffi:defcenum event-type
  (:none 0)
  (:push 1)
  (:release 2)
  (:doubleclick 4)
  (:drag 8)
  (:move 16)
  (:keydown 32)
  (:keyup 64)
  (:frame 128)
  (:resize 256)
  (:scroll 512)
  (:pen-pressure 1024)
  (:pen-orientation 2048)
  (:pen-proximity-enter 4096)
  (:pen-proximity-leave 8192)
  (:close-window 16384)
  (:quit-application 32768)
  (:user 65536))

(cffi:defcenum scrolling-motion
  (:scroll-none 0)
  (:scroll-left 1)
  (:scroll-right 2)
  (:scroll-up 3)
  (:scroll-down 4)
  (:scroll-2d 5))

(cffi:defcenum mouse-y-orientation
  (:y-increasing-upwards 0)
  (:y-increasing-downwards 1))

(cffi:defcenum tablet-pointer-type
  (:unknown 0)
  (:pen 1)
  (:puck 2)
  (:eraser 3))

(cffi:defcstruct gui-event-adapter
  (_handled :char)
  (_event-type event-type)
  (_time :double)
  (_context observer-ptr-<osg-::-graphics-context->)
  (_window-x :int)
  (_window-y :int)
  (_window-width :int)
  (_window-height :int)
  (_key :int)
  (_button :int)
  (_-xmin :float)
  (_-xmax :float)
  (_-ymin :float)
  (_-ymax :float)
  (_mx :float)
  (_my :float)
  (_pressure :float)
  (_tilt-x :float)
  (_tilt-y :float)
  (_rotation :float)
  (_button-mask :unsigned-int)
  (_mod-key-mask :unsigned-int)
  (_scrolling-motion scrolling-motion)
  (_scrolling-delta-x :float)
  (_scrolling-delta-y :float)
  (_mouse-y-orientation mouse-y-orientation)
  (_tablet-pointer-type tablet-pointer-type))

(cffi:defcstruct gui-action-adapter
  )

(cffi:defcfun ("_ZN5osgGA20TrackballManipulator4homeERKNS_15GUIEventAdapterERNS_16GUIActionAdapterE" home) :void (this :pointer)
                                                                                                                 (ea gui-event-adapter)
                                                                                                                 (us gui-action-adapter))

(cffi:defcfun ("_ZN5osgGA20TrackballManipulator4homeEd" home) :void (this :pointer) (arg1 :double))

(cffi:defcfun ("_ZN5osgGA20TrackballManipulator4initERKNS_15GUIEventAdapterERNS_16GUIActionAdapterE" init) :void (this :pointer)
                                                                                                                 (ea gui-event-adapter)
                                                                                                                 (us gui-action-adapter))

(cffi:defcfun ("_ZN5osgGA20TrackballManipulator6handleERKNS_15GUIEventAdapterERNS_16GUIActionAdapterE" handle) :char (this :pointer)
                                                                                                                     (ea gui-event-adapter)
                                                                                                                     (us gui-action-adapter))

(cffi::defctype string basic-string-<char-,std-::char-traits-<char->,std-::allocator-<char-> >)

(cffi:defcstruct application-usage
  (_application-name string)
  (_description string)
  (_command-line-usage string)
  (_command-line-options map-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >,std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >,std-::less-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> > >,std-::allocator-<std-::pair-<const- std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >, std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> > > > >)
  (_environmental-variables map-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >,std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >,std-::less-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> > >,std-::allocator-<std-::pair-<const- std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >, std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> > > > >)
  (_keyboard-mouse map-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >,std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >,std-::less-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> > >,std-::allocator-<std-::pair-<const- std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >, std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> > > > >)
  (_environmental-variables-defaults map-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >,std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >,std-::less-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> > >,std-::allocator-<std-::pair-<const- std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >, std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> > > > >)
  (_command-line-options-defaults map-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >,std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >,std-::less-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> > >,std-::allocator-<std-::pair-<const- std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >, std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> > > > >))

(cffi:defcfun ("_ZNK5osgGA20TrackballManipulator8getUsageERN3osg16ApplicationUsageE" get-usage) :void (this :pointer)
                                                                                                      (usage application-usage))

(cffi:defcfun ("_ZN5osgGA20TrackballManipulator19setMinimumZoomScaleEd" set-minimum-zoom-scale) :void (this :pointer)
                                                                                                      (minimum-zoom-scale :double))

(cffi:defcfun ("_ZNK5osgGA20TrackballManipulator19getMinimumZoomScaleEv" get-minimum-zoom-scale) :double (this :pointer))

(cffi:defcfun ("_ZN5osgGA20TrackballManipulator9setCenterERKN3osg5Vec3dE" set-center) :void (this :pointer)
                                                                                            (center vec-3d))

(cffi:defcfun ("_ZNK5osgGA20TrackballManipulator9getCenterEv" get-center) vec-3d (this :pointer))

(cffi:defcfun ("_ZN5osgGA20TrackballManipulator11setRotationERKN3osg4QuatE" set-rotation) :void (this :pointer)
                                                                                                (rotation quat))

(cffi:defcfun ("_ZNK5osgGA20TrackballManipulator11getRotationEv" get-rotation) quat (this :pointer))

(cffi:defcfun ("_ZN5osgGA20TrackballManipulator11setDistanceEd" set-distance) :void (this :pointer)
                                                                                    (distance :double))

(cffi:defcfun ("_ZNK5osgGA20TrackballManipulator11getDistanceEv" get-distance) :double (this :pointer))

(cffi:defcfun ("_ZN5osgGA20TrackballManipulator16setTrackballSizeEf" set-trackball-size) :void (this :pointer)
                                                                                               (size :float))

(cffi:defcfun ("_ZNK5osgGA20TrackballManipulator16getTrackballSizeEv" get-trackball-size) :float (this :pointer))

(cffi:defcfun ("_ZN5osgGA20TrackballManipulator20flushMouseEventStackEv" flush-mouse-event-stack) :void (this :pointer))

(cffi:defcfun ("_ZN5osgGA20TrackballManipulator13addMouseEventERKNS_15GUIEventAdapterE" add-mouse-event) :void (this :pointer)
                                                                                                               (ea gui-event-adapter))

(cffi:defcstruct vec-3f
  (_v :float :count 3))

(cffi::defctype vec-3 vec-3f)

(cffi:defcfun ("_ZN5osgGA20TrackballManipulator15computePositionERKN3osg5Vec3fES4_S4_" compute-position) :void (this :pointer)
                                                                                                               (eye vec-3)
                                                                                                               (lv vec-3)
                                                                                                               (up vec-3))

(cffi:defcfun ("_ZN5osgGA20TrackballManipulator12calcMovementEv" calc-movement) :char (this :pointer))

(cffi:defcfun ("_ZN5osgGA20TrackballManipulator9trackballERN3osg5Vec3fERfffff" trackball) :void (this :pointer)
                                                                                                (axis vec-3)
                                                                                                (angle :float)
                                                                                                (p-1x :float)
                                                                                                (p-1y :float)
                                                                                                (p-2x :float)
                                                                                                (p-2y :float))

(cffi:defcfun ("_ZN5osgGA20TrackballManipulator20tb_project_to_sphereEfff" tb-project-to-sphere) :float (this :pointer)
                                                                                                        (r :float)
                                                                                                        (x :float)
                                                                                                        (y :float))

(cffi:defcfun ("_ZN5osgGA20TrackballManipulator13isMouseMovingEv" is-mouse-moving) :char (this :pointer))
