;;; Generated by Verrazano 0.5
;;; WARNING: This is a generated file, editing it is unwise!


(cl:in-package :cl-user)

(cl:defpackage :osg-db-cffi-bindings
  (:use :cffi)
  (:nicknames)
  (:export "READ-IMAGE-FILE"
           "REF-PTR-<OSG-::-PIXEL-BUFFER-OBJECT->"
           "VECTOR-<UNSIGNED- INT-,STD-::ALLOCATOR-<UNSIGNED- INT-> >"
           "IMAGE"
           "USE-MALLOC-FREE"
           "USE-NEW-DELETE"
           "NO-DELETE"
           "ALLOCATION-MODE"
           "G-LENUM"
           "G-LINT"
           "TOP-LEFT"
           "BOTTOM-LEFT"
           "ORIGIN"
           "EXTERNAL-FILE"
           "STORE-INLINE"
           "WRITE-HINT"
           "READ-NODE-FILES"
           "REF-PTR-<OSG-::-APPLICATION-USAGE->"
           "MAP-<STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> >,OSG-::-ARGUMENT-PARSER-::-ERROR-SEVERITY-,STD-::LESS-<STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> > >,STD-::ALLOCATOR-<STD-::PAIR-<CONST- STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> >, OSG-::-ARGUMENT-PARSER-::-ERROR-SEVERITY-> > >"
           "ARGUMENT-PARSER"
           "REF-PTR-<OSG-::-OBJECT->"
           "READ-REF-OBJECT-FILE"
           "READ-HEIGHT-FIELD-FILE"
           "REF-PTR-<OSG-::-TEMPLATE-ARRAY-<FLOAT-, -FLOAT-ARRAY-TYPE-, 1, 5126> >"
           "HEIGHT-FIELD"
           "QUAT"
           "VEC-3"
           "VEC-3F"
           "REF-PTR-<OSG-::-HEIGHT-FIELD->"
           "READ-REF-HEIGHT-FIELD-FILE"
           "READ-OBJECT-FILE"
           "REF-PTR-<OSG-::-REFERENCED->"
           "OBJECT"
           "UNSPECIFIED"
           "STATIC"
           "DYNAMIC"
           "DATA-VARIANCE"
           "REF-PTR-<OSG-::-SHADER->"
           "READ-REF-SHADER-FILE"
           "READ-NODE-FILE"
           "REF-PTR-<OSG-::-STATE-SET->"
           "VECTOR-<STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> >,STD-::ALLOCATOR-<STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> > > >"
           "REF-PTR-<OSG-::-NODE-CALLBACK->"
           "VECTOR-<OSG-::-GROUP-*,STD-::ALLOCATOR-<OSG-::-GROUP-*> >"
           "REF-PTR-<OSG-::-NODE-::-COMPUTE-BOUNDING-SPHERE-CALLBACK->"
           "NODE"
           "BOUNDING-SPHERE"
           "BOUNDING-SPHERE-IMPL-<OSG-::-VEC-3F->"
           "BOUNDING-SPHEREF"
           "READ-SHADER-FILE"
           "BUFFERED-VALUE-<OSG-::REF-PTR-<OSG-::-SHADER-::-PER-CONTEXT-SHADER-> >"
           "SET-<OSG-::-PROGRAM-*,STD-::LESS-<OSG-::-PROGRAM-*>,STD-::ALLOCATOR-<OSG-::-PROGRAM-*> >"
           "SHADER"
           "UNDEFINED"
           "GEOMETRY"
           "FRAGMENT"
           "VERTEX"
           "TYPE"
           "REF-PTR-<OSG-::-IMAGE->"
           "READ-REF-IMAGE-FILE"
           "MAP-<STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> >,VOID-*,STD-::LESS-<STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> > >,STD-::ALLOCATOR-<STD-::PAIR-<CONST- STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> >, VOID-*> > >"
           "REF-PTR-<OSG-DB-::-AUTHENTICATION-MAP->"
           "OPTIONS"
           "BUILD-KDTREES"
           "DO-NOT-BUILD-KDTREES"
           "NO-PREFERENCE"
           "BUILD-KD-TREES-HINT"
           "CACHE-ALL"
           "CACHE-SHADERS"
           "CACHE-OBJECTS"
           "CACHE-ARCHIVES"
           "CACHE-HEIGHTFIELDS"
           "CACHE-IMAGES"
           "CACHE-NODES"
           "CACHE-NONE"
           "CACHE-HINT-OPTIONS"
           "DEQUE-<STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> >,STD-::ALLOCATOR-<STD-::BASIC-STRING-<CHAR-, STD-::CHAR-TRAITS-<CHAR->, STD-::ALLOCATOR-<CHAR-> > > >"
           "FILE-PATH-LIST"
           "REF-PTR-<OSG-::-NODE->"
           "READ-REF-NODE-FILE"
           "BASIC-STRING-<CHAR-,STD-::CHAR-TRAITS-<CHAR->,STD-::ALLOCATOR-<CHAR-> >"
           "STRING"))

(cl:in-package :osg-db-cffi-bindings)

(cl:defun vtable-lookup (pobj indx coff)
  (cl:let ((vptr (cffi:mem-ref pobj :pointer coff)))
    (cffi:mem-aref vptr :pointer (cl:- indx 2))))

(cl:defmacro virtual-funcall (pobj indx coff cl:&body body)
  `(cffi:foreign-funcall-pointer (vtable-lookup ,pobj ,indx ,coff) ,cl:nil ,@body))

(cffi::defctype string basic-string-<char-,std-::char-traits-<char->,std-::allocator-<char-> >)

(cffi:defcfun ("_ZN5osgDB15readRefNodeFileERKSs" read-ref-node-file) ref-ptr-<osg-::-node->
                                                                                            (filename string))

(cffi::defctype file-path-list deque-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >,std-::allocator-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> > > >)

(cffi:defcenum cache-hint-options
  (:cache-none 0)
  (:cache-nodes 1)
  (:cache-images 2)
  (:cache-heightfields 4)
  (:cache-archives 8)
  (:cache-objects 16)
  (:cache-shaders 32)
  (:cache-all 63))

(cffi:defcenum build-kd-trees-hint
  (:no-preference 0)
  (:do-not-build-kdtrees 1)
  (:build-kdtrees 2))

(cffi:defcstruct options
  (_str string)
  (_database-paths file-path-list)
  (_object-cache-hint cache-hint-options)
  (_build-kd-trees-hint build-kd-trees-hint)
  (_authentication-map ref-ptr-<osg-db-::-authentication-map->)
  (_plugin-data map-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >,void-*,std-::less-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> > >,std-::allocator-<std-::pair-<const- std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >, void-*> > >))

(cffi:defcfun ("_ZN5osgDB15readRefNodeFileERKSsPKNS_12ReaderWriter7OptionsE" read-ref-node-file) ref-ptr-<osg-::-node->
                                                                                                                        (filename string)
                                                                                                                        (options :pointer))

(cffi:defcfun ("_ZN5osgDB16readRefImageFileERKSs" read-ref-image-file) ref-ptr-<osg-::-image->
                                                                                               (filename string))

(cffi:defcfun ("_ZN5osgDB16readRefImageFileERKSsPKNS_12ReaderWriter7OptionsE" read-ref-image-file) ref-ptr-<osg-::-image->
                                                                                                                           (filename string)
                                                                                                                           (options :pointer))

(cffi:defcenum type
  (:vertex 35633)
  (:fragment 35632)
  (:geometry 36313)
  (:undefined -1))

(cffi:defcstruct shader
  (_type type)
  (_shader-source string)
  (_shader-file-name string)
  (_program-set set-<osg-::-program-*,std-::less-<osg-::-program-*>,std-::allocator-<osg-::-program-*> >)
  (_pcs-list buffered-value-<osg-::ref-ptr-<osg-::-shader-::-per-context-shader-> >))

(cffi:defcfun ("_ZN5osgDB14readShaderFileEN3osg6Shader4TypeERKSs" read-shader-file) :pointer
                                                                                             (type type)
                                                                                             (filename string))

(cffi:defcfun ("_ZN5osgDB14readShaderFileEN3osg6Shader4TypeERKSsPKNS_12ReaderWriter7OptionsE" read-shader-file) :pointer
                                                                                                                         (type type)
                                                                                                                         (filename string)
                                                                                                                         (options :pointer))

(cffi:defcfun ("_ZN5osgDB14readShaderFileERKSs" read-shader-file) :pointer (filename string))

(cffi:defcfun ("_ZN5osgDB14readShaderFileERKSsPKNS_12ReaderWriter7OptionsE" read-shader-file) :pointer
                                                                                                       (filename string)
                                                                                                       (options :pointer))

(cffi::defctype bounding-spheref bounding-sphere-impl-<osg-::-vec-3f->)

(cffi::defctype bounding-sphere bounding-spheref)

(cffi:defcstruct node
  (_initial-bound bounding-sphere)
  (_compute-bound-callback ref-ptr-<osg-::-node-::-compute-bounding-sphere-callback->)
  (_bounding-sphere bounding-sphere)
  (_bounding-sphere-computed :char)
  (_parents vector-<osg-::-group-*,std-::allocator-<osg-::-group-*> >)
  (_update-callback ref-ptr-<osg-::-node-callback->)
  (_num-children-requiring-update-traversal :unsigned-int)
  (_event-callback ref-ptr-<osg-::-node-callback->)
  (_num-children-requiring-event-traversal :unsigned-int)
  (_cull-callback ref-ptr-<osg-::-node-callback->)
  (_culling-active :char)
  (_num-children-with-culling-disabled :unsigned-int)
  (_num-children-with-occluder-nodes :unsigned-int)
  (_node-mask :unsigned-int)
  (_descriptions vector-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >,std-::allocator-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> > > >)
  (_stateset ref-ptr-<osg-::-state-set->))

(cffi:defcfun ("_ZN5osgDB12readNodeFileERKSs" read-node-file) :pointer (filename string))

(cffi:defcfun ("_ZN5osgDB12readNodeFileERKSsPKNS_12ReaderWriter7OptionsE" read-node-file) :pointer
                                                                                                   (filename string)
                                                                                                   (options :pointer))

(cffi:defcfun ("_ZN5osgDB17readRefShaderFileERKSs" read-ref-shader-file) ref-ptr-<osg-::-shader->
                                                                                                  (filename string))

(cffi:defcfun ("_ZN5osgDB17readRefShaderFileERKSsPKNS_12ReaderWriter7OptionsE" read-ref-shader-file) ref-ptr-<osg-::-shader->
                                                                                                                              (filename string)
                                                                                                                              (options :pointer))

(cffi:defcenum data-variance
  (:dynamic 0)
  (:static 1)
  (:unspecified 2))

(cffi:defcstruct object
  (_name string)
  (_data-variance data-variance)
  (_user-data ref-ptr-<osg-::-referenced->))

(cffi:defcfun ("_ZN5osgDB14readObjectFileERKSs" read-object-file) :pointer (filename string))

(cffi:defcfun ("_ZN5osgDB14readObjectFileERKSsPKNS_12ReaderWriter7OptionsE" read-object-file) :pointer
                                                                                                       (filename string)
                                                                                                       (options :pointer))

(cffi:defcfun ("_ZN5osgDB22readRefHeightFieldFileERKSs" read-ref-height-field-file) ref-ptr-<osg-::-height-field->
                                                                                                                   (filename string))

(cffi:defcfun ("_ZN5osgDB22readRefHeightFieldFileERKSsPKNS_12ReaderWriter7OptionsE" read-ref-height-field-file) ref-ptr-<osg-::-height-field->
                                                                                                                                               (filename string)
                                                                                                                                               (options :pointer))

(cffi:defcstruct vec-3f
  (_v :float :count 3))

(cffi::defctype vec-3 vec-3f)

(cffi:defcstruct quat
  (_v :double :count 4))

(cffi:defcstruct height-field
  (_columns :unsigned-int)
  (_rows :unsigned-int)
  (_origin vec-3)
  (_dx :float)
  (_dy :float)
  (_skirt-height :float)
  (_border-width :unsigned-int)
  (_rotation quat)
  (_heights ref-ptr-<osg-::-template-array-<float-, -float-array-type-, 1, 5126> >))

(cffi:defcfun ("_ZN5osgDB19readHeightFieldFileERKSs" read-height-field-file) :pointer
                                                                                      (filename string))

(cffi:defcfun ("_ZN5osgDB19readHeightFieldFileERKSsPKNS_12ReaderWriter7OptionsE" read-height-field-file) :pointer
                                                                                                                  (filename string)
                                                                                                                  (options :pointer))

(cffi:defcfun ("_ZN5osgDB17readRefObjectFileERKSs" read-ref-object-file) ref-ptr-<osg-::-object->
                                                                                                  (filename string))

(cffi:defcfun ("_ZN5osgDB17readRefObjectFileERKSsPKNS_12ReaderWriter7OptionsE" read-ref-object-file) ref-ptr-<osg-::-object->
                                                                                                                              (filename string)
                                                                                                                              (options :pointer))

(cffi:defcstruct argument-parser
  (_argc (:pointer :int))
  (_argv :pointer)
  (_error-message-map map-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >,osg-::-argument-parser-::-error-severity-,std-::less-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> > >,std-::allocator-<std-::pair-<const- std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >, osg-::-argument-parser-::-error-severity-> > >)
  (_usage ref-ptr-<osg-::-application-usage->))

(cffi:defcfun ("_ZN5osgDB13readNodeFilesERN3osg14ArgumentParserE" read-node-files) :pointer
                                                                                            (parser argument-parser))

(cffi:defcfun ("_ZN5osgDB13readNodeFilesERN3osg14ArgumentParserEPKNS_12ReaderWriter7OptionsE" read-node-files) :pointer
                                                                                                                        (parser argument-parser)
                                                                                                                        (options :pointer))

(cffi:defcfun ("_ZN5osgDB13readNodeFilesERSt6vectorISsSaISsEE" read-node-files) :pointer
                                                                                         (command-line vector-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >,std-::allocator-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> > > >))

(cffi:defcfun ("_ZN5osgDB13readNodeFilesERSt6vectorISsSaISsEEPKNS_12ReaderWriter7OptionsE" read-node-files) :pointer
                                                                                                                     (command-line vector-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> >,std-::allocator-<std-::basic-string-<char-, std-::char-traits-<char->, std-::allocator-<char-> > > >)
                                                                                                                     (options :pointer))

(cffi:defcenum write-hint
  (:no-preference 0)
  (:store-inline 1)
  (:external-file 2))

(cffi:defcenum origin
  (:bottom-left 0)
  (:top-left 1))

(cffi::defctype g-lint :int)

(cffi::defctype g-lenum :unsigned-int)

(cffi:defcenum allocation-mode
  (:no-delete 0)
  (:use-new-delete 1)
  (:use-malloc-free 2))

(cffi:defcstruct image
  (_file-name string)
  (_write-hint write-hint)
  (_origin origin)
  (_s :int)
  (_t :int)
  (_r :int)
  (_internal-texture-format g-lint)
  (_pixel-format g-lenum)
  (_data-type g-lenum)
  (_packing :unsigned-int)
  (_allocation-mode allocation-mode)
  (_data (:pointer :unsigned-char))
  (_modified-count :unsigned-int)
  (_mipmap-data vector-<unsigned- int-,std-::allocator-<unsigned- int-> >)
  (_buffer-object ref-ptr-<osg-::-pixel-buffer-object->))

(cffi:defcfun ("_ZN5osgDB13readImageFileERKSs" read-image-file) :pointer (filename string))

(cffi:defcfun ("_ZN5osgDB13readImageFileERKSsPKNS_12ReaderWriter7OptionsE" read-image-file) :pointer
                                                                                                     (filename string)
                                                                                                     (options :pointer))
